import { DataSource } from "typeorm";
import { Country } from "../../entities";

export class CountryDataSeeder {
    
    static async seed(dataSource: DataSource): Promise<void> {
        const countryRepository = dataSource.getRepository(Country);
        
        // Check if countries already exist
        const existingCount = await countryRepository.count();
        if (existingCount > 0) {
            console.log('Countries already seeded, skipping...');
            return;
        }

        const countries = [
            { name: "Afghanistan", code: "AFG", iso2: "AF", capital: "Kabul", continent: "Asia", currency: "AFN", phone: "+93" },
            { name: "Albania", code: "ALB", iso2: "AL", capital: "Tirana", continent: "Europe", currency: "ALL", phone: "+355" },
            { name: "Algeria", code: "DZA", iso2: "DZ", capital: "Algiers", continent: "Africa", currency: "DZD", phone: "+213" },
            { name: "Andorra", code: "AND", iso2: "AD", capital: "Andorra la Vella", continent: "Europe", currency: "EUR", phone: "+376" },
            { name: "Angola", code: "AGO", iso2: "AO", capital: "Luanda", continent: "Africa", currency: "AOA", phone: "+244" },
            { name: "Argentina", code: "ARG", iso2: "AR", capital: "Buenos Aires", continent: "South America", currency: "ARS", phone: "+54" },
            { name: "Armenia", code: "ARM", iso2: "AM", capital: "Yerevan", continent: "Asia", currency: "AMD", phone: "+374" },
            { name: "Australia", code: "AUS", iso2: "AU", capital: "Canberra", continent: "Oceania", currency: "AUD", phone: "+61" },
            { name: "Austria", code: "AUT", iso2: "AT", capital: "Vienna", continent: "Europe", currency: "EUR", phone: "+43" },
            { name: "Azerbaijan", code: "AZE", iso2: "AZ", capital: "Baku", continent: "Asia", currency: "AZN", phone: "+994" },
            { name: "Bahamas", code: "BHS", iso2: "BS", capital: "Nassau", continent: "North America", currency: "BSD", phone: "+1242" },
            { name: "Bahrain", code: "BHR", iso2: "BH", capital: "Manama", continent: "Asia", currency: "BHD", phone: "+973" },
            { name: "Bangladesh", code: "BGD", iso2: "BD", capital: "Dhaka", continent: "Asia", currency: "BDT", phone: "+880" },
            { name: "Barbados", code: "BRB", iso2: "BB", capital: "Bridgetown", continent: "North America", currency: "BBD", phone: "+1246" },
            { name: "Belarus", code: "BLR", iso2: "BY", capital: "Minsk", continent: "Europe", currency: "BYN", phone: "+375" },
            { name: "Belgium", code: "BEL", iso2: "BE", capital: "Brussels", continent: "Europe", currency: "EUR", phone: "+32" },
            { name: "Belize", code: "BLZ", iso2: "BZ", capital: "Belmopan", continent: "North America", currency: "BZD", phone: "+501" },
            { name: "Benin", code: "BEN", iso2: "BJ", capital: "Porto-Novo", continent: "Africa", currency: "XOF", phone: "+229" },
            { name: "Bhutan", code: "BTN", iso2: "BT", capital: "Thimphu", continent: "Asia", currency: "BTN", phone: "+975" },
            { name: "Bolivia", code: "BOL", iso2: "BO", capital: "Sucre", continent: "South America", currency: "BOB", phone: "+591" },
            { name: "Bosnia and Herzegovina", code: "BIH", iso2: "BA", capital: "Sarajevo", continent: "Europe", currency: "BAM", phone: "+387" },
            { name: "Botswana", code: "BWA", iso2: "BW", capital: "Gaborone", continent: "Africa", currency: "BWP", phone: "+267" },
            { name: "Brazil", code: "BRA", iso2: "BR", capital: "Brasília", continent: "South America", currency: "BRL", phone: "+55" },
            { name: "Brunei", code: "BRN", iso2: "BN", capital: "Bandar Seri Begawan", continent: "Asia", currency: "BND", phone: "+673" },
            { name: "Bulgaria", code: "BGR", iso2: "BG", capital: "Sofia", continent: "Europe", currency: "BGN", phone: "+359" },
            { name: "Burkina Faso", code: "BFA", iso2: "BF", capital: "Ouagadougou", continent: "Africa", currency: "XOF", phone: "+226" },
            { name: "Burundi", code: "BDI", iso2: "BI", capital: "Gitega", continent: "Africa", currency: "BIF", phone: "+257" },
            { name: "Cambodia", code: "KHM", iso2: "KH", capital: "Phnom Penh", continent: "Asia", currency: "KHR", phone: "+855" },
            { name: "Cameroon", code: "CMR", iso2: "CM", capital: "Yaoundé", continent: "Africa", currency: "XAF", phone: "+237" },
            { name: "Canada", code: "CAN", iso2: "CA", capital: "Ottawa", continent: "North America", currency: "CAD", phone: "+1" },
            { name: "Cape Verde", code: "CPV", iso2: "CV", capital: "Praia", continent: "Africa", currency: "CVE", phone: "+238" },
            { name: "Central African Republic", code: "CAF", iso2: "CF", capital: "Bangui", continent: "Africa", currency: "XAF", phone: "+236" },
            { name: "Chad", code: "TCD", iso2: "TD", capital: "N'Djamena", continent: "Africa", currency: "XAF", phone: "+235" },
            { name: "Chile", code: "CHL", iso2: "CL", capital: "Santiago", continent: "South America", currency: "CLP", phone: "+56" },
            { name: "China", code: "CHN", iso2: "CN", capital: "Beijing", continent: "Asia", currency: "CNY", phone: "+86" },
            { name: "Colombia", code: "COL", iso2: "CO", capital: "Bogotá", continent: "South America", currency: "COP", phone: "+57" },
            { name: "Comoros", code: "COM", iso2: "KM", capital: "Moroni", continent: "Africa", currency: "KMF", phone: "+269" },
            { name: "Congo", code: "COG", iso2: "CG", capital: "Brazzaville", continent: "Africa", currency: "XAF", phone: "+242" },
            { name: "Costa Rica", code: "CRI", iso2: "CR", capital: "San José", continent: "North America", currency: "CRC", phone: "+506" },
            { name: "Croatia", code: "HRV", iso2: "HR", capital: "Zagreb", continent: "Europe", currency: "EUR", phone: "+385" },
            { name: "Cuba", code: "CUB", iso2: "CU", capital: "Havana", continent: "North America", currency: "CUP", phone: "+53" },
            { name: "Cyprus", code: "CYP", iso2: "CY", capital: "Nicosia", continent: "Europe", currency: "EUR", phone: "+357" },
            { name: "Czech Republic", code: "CZE", iso2: "CZ", capital: "Prague", continent: "Europe", currency: "CZK", phone: "+420" },
            { name: "Democratic Republic of the Congo", code: "COD", iso2: "CD", capital: "Kinshasa", continent: "Africa", currency: "CDF", phone: "+243" },
            { name: "Denmark", code: "DNK", iso2: "DK", capital: "Copenhagen", continent: "Europe", currency: "DKK", phone: "+45" },
            { name: "Djibouti", code: "DJI", iso2: "DJ", capital: "Djibouti", continent: "Africa", currency: "DJF", phone: "+253" },
            { name: "Dominica", code: "DMA", iso2: "DM", capital: "Roseau", continent: "North America", currency: "XCD", phone: "+1767" },
            { name: "Dominican Republic", code: "DOM", iso2: "DO", capital: "Santo Domingo", continent: "North America", currency: "DOP", phone: "+1809" },
            { name: "Ecuador", code: "ECU", iso2: "EC", capital: "Quito", continent: "South America", currency: "USD", phone: "+593" },
            { name: "Egypt", code: "EGY", iso2: "EG", capital: "Cairo", continent: "Africa", currency: "EGP", phone: "+20" },
            { name: "El Salvador", code: "SLV", iso2: "SV", capital: "San Salvador", continent: "North America", currency: "USD", phone: "+503" },
            { name: "Equatorial Guinea", code: "GNQ", iso2: "GQ", capital: "Malabo", continent: "Africa", currency: "XAF", phone: "+240" },
            { name: "Eritrea", code: "ERI", iso2: "ER", capital: "Asmara", continent: "Africa", currency: "ERN", phone: "+291" },
            { name: "Estonia", code: "EST", iso2: "EE", capital: "Tallinn", continent: "Europe", currency: "EUR", phone: "+372" },
            { name: "Eswatini", code: "SWZ", iso2: "SZ", capital: "Mbabane", continent: "Africa", currency: "SZL", phone: "+268" },
            { name: "Ethiopia", code: "ETH", iso2: "ET", capital: "Addis Ababa", continent: "Africa", currency: "ETB", phone: "+251" },
            { name: "Fiji", code: "FJI", iso2: "FJ", capital: "Suva", continent: "Oceania", currency: "FJD", phone: "+679" },
            { name: "Finland", code: "FIN", iso2: "FI", capital: "Helsinki", continent: "Europe", currency: "EUR", phone: "+358" },
            { name: "France", code: "FRA", iso2: "FR", capital: "Paris", continent: "Europe", currency: "EUR", phone: "+33" },
            { name: "Gabon", code: "GAB", iso2: "GA", capital: "Libreville", continent: "Africa", currency: "XAF", phone: "+241" },
            { name: "Gambia", code: "GMB", iso2: "GM", capital: "Banjul", continent: "Africa", currency: "GMD", phone: "+220" },
            { name: "Georgia", code: "GEO", iso2: "GE", capital: "Tbilisi", continent: "Asia", currency: "GEL", phone: "+995" },
            { name: "Germany", code: "DEU", iso2: "DE", capital: "Berlin", continent: "Europe", currency: "EUR", phone: "+49" },
            { name: "Ghana", code: "GHA", iso2: "GH", capital: "Accra", continent: "Africa", currency: "GHS", phone: "+233" },
            { name: "Greece", code: "GRC", iso2: "GR", capital: "Athens", continent: "Europe", currency: "EUR", phone: "+30" },
            { name: "Grenada", code: "GRD", iso2: "GD", capital: "St. George's", continent: "North America", currency: "XCD", phone: "+1473" },
            { name: "Guatemala", code: "GTM", iso2: "GT", capital: "Guatemala City", continent: "North America", currency: "GTQ", phone: "+502" },
            { name: "Guinea", code: "GIN", iso2: "GN", capital: "Conakry", continent: "Africa", currency: "GNF", phone: "+224" },
            { name: "Guinea-Bissau", code: "GNB", iso2: "GW", capital: "Bissau", continent: "Africa", currency: "XOF", phone: "+245" },
            { name: "Guyana", code: "GUY", iso2: "GY", capital: "Georgetown", continent: "South America", currency: "GYD", phone: "+592" },
            { name: "Haiti", code: "HTI", iso2: "HT", capital: "Port-au-Prince", continent: "North America", currency: "HTG", phone: "+509" },
            { name: "Honduras", code: "HND", iso2: "HN", capital: "Tegucigalpa", continent: "North America", currency: "HNL", phone: "+504" },
            { name: "Hungary", code: "HUN", iso2: "HU", capital: "Budapest", continent: "Europe", currency: "HUF", phone: "+36" },
            { name: "Iceland", code: "ISL", iso2: "IS", capital: "Reykjavik", continent: "Europe", currency: "ISK", phone: "+354" },
            { name: "India", code: "IND", iso2: "IN", capital: "New Delhi", continent: "Asia", currency: "INR", phone: "+91" },
            { name: "Indonesia", code: "IDN", iso2: "ID", capital: "Jakarta", continent: "Asia", currency: "IDR", phone: "+62" },
            { name: "Iran", code: "IRN", iso2: "IR", capital: "Tehran", continent: "Asia", currency: "IRR", phone: "+98" },
            { name: "Iraq", code: "IRQ", iso2: "IQ", capital: "Baghdad", continent: "Asia", currency: "IQD", phone: "+964" },
            { name: "Ireland", code: "IRL", iso2: "IE", capital: "Dublin", continent: "Europe", currency: "EUR", phone: "+353" },
            { name: "Israel", code: "ISR", iso2: "IL", capital: "Jerusalem", continent: "Asia", currency: "ILS", phone: "+972" },
            { name: "Italy", code: "ITA", iso2: "IT", capital: "Rome", continent: "Europe", currency: "EUR", phone: "+39" },
            { name: "Jamaica", code: "JAM", iso2: "JM", capital: "Kingston", continent: "North America", currency: "JMD", phone: "+1876" },
            { name: "Japan", code: "JPN", iso2: "JP", capital: "Tokyo", continent: "Asia", currency: "JPY", phone: "+81" },
            { name: "Jordan", code: "JOR", iso2: "JO", capital: "Amman", continent: "Asia", currency: "JOD", phone: "+962" },
            { name: "Kazakhstan", code: "KAZ", iso2: "KZ", capital: "Nur-Sultan", continent: "Asia", currency: "KZT", phone: "+7" },
            { name: "Kenya", code: "KEN", iso2: "KE", capital: "Nairobi", continent: "Africa", currency: "KES", phone: "+254" },
            { name: "Kiribati", code: "KIR", iso2: "KI", capital: "Tarawa", continent: "Oceania", currency: "AUD", phone: "+686" },
            { name: "Kuwait", code: "KWT", iso2: "KW", capital: "Kuwait City", continent: "Asia", currency: "KWD", phone: "+965" },
            { name: "Kyrgyzstan", code: "KGZ", iso2: "KG", capital: "Bishkek", continent: "Asia", currency: "KGS", phone: "+996" },
            { name: "Laos", code: "LAO", iso2: "LA", capital: "Vientiane", continent: "Asia", currency: "LAK", phone: "+856" },
            { name: "Latvia", code: "LVA", iso2: "LV", capital: "Riga", continent: "Europe", currency: "EUR", phone: "+371" },
            { name: "Lebanon", code: "LBN", iso2: "LB", capital: "Beirut", continent: "Asia", currency: "LBP", phone: "+961" },
            { name: "Lesotho", code: "LSO", iso2: "LS", capital: "Maseru", continent: "Africa", currency: "LSL", phone: "+266" },
            { name: "Liberia", code: "LBR", iso2: "LR", capital: "Monrovia", continent: "Africa", currency: "LRD", phone: "+231" },
            { name: "Libya", code: "LBY", iso2: "LY", capital: "Tripoli", continent: "Africa", currency: "LYD", phone: "+218" },
            { name: "Liechtenstein", code: "LIE", iso2: "LI", capital: "Vaduz", continent: "Europe", currency: "CHF", phone: "+423" },
            { name: "Lithuania", code: "LTU", iso2: "LT", capital: "Vilnius", continent: "Europe", currency: "EUR", phone: "+370" },
            { name: "Luxembourg", code: "LUX", iso2: "LU", capital: "Luxembourg", continent: "Europe", currency: "EUR", phone: "+352" },
            { name: "Madagascar", code: "MDG", iso2: "MG", capital: "Antananarivo", continent: "Africa", currency: "MGA", phone: "+261" },
            { name: "Malawi", code: "MWI", iso2: "MW", capital: "Lilongwe", continent: "Africa", currency: "MWK", phone: "+265" },
            { name: "Malaysia", code: "MYS", iso2: "MY", capital: "Kuala Lumpur", continent: "Asia", currency: "MYR", phone: "+60" },
            { name: "Maldives", code: "MDV", iso2: "MV", capital: "Malé", continent: "Asia", currency: "MVR", phone: "+960" },
            { name: "Mali", code: "MLI", iso2: "ML", capital: "Bamako", continent: "Africa", currency: "XOF", phone: "+223" },
            { name: "Malta", code: "MLT", iso2: "MT", capital: "Valletta", continent: "Europe", currency: "EUR", phone: "+356" },
            { name: "Marshall Islands", code: "MHL", iso2: "MH", capital: "Majuro", continent: "Oceania", currency: "USD", phone: "+692" },
            { name: "Mauritania", code: "MRT", iso2: "MR", capital: "Nouakchott", continent: "Africa", currency: "MRU", phone: "+222" },
            { name: "Mauritius", code: "MUS", iso2: "MU", capital: "Port Louis", continent: "Africa", currency: "MUR", phone: "+230" },
            { name: "Mexico", code: "MEX", iso2: "MX", capital: "Mexico City", continent: "North America", currency: "MXN", phone: "+52" },
            { name: "Micronesia", code: "FSM", iso2: "FM", capital: "Palikir", continent: "Oceania", currency: "USD", phone: "+691" },
            { name: "Moldova", code: "MDA", iso2: "MD", capital: "Chișinău", continent: "Europe", currency: "MDL", phone: "+373" },
            { name: "Monaco", code: "MCO", iso2: "MC", capital: "Monaco", continent: "Europe", currency: "EUR", phone: "+377" },
            { name: "Mongolia", code: "MNG", iso2: "MN", capital: "Ulaanbaatar", continent: "Asia", currency: "MNT", phone: "+976" },
            { name: "Montenegro", code: "MNE", iso2: "ME", capital: "Podgorica", continent: "Europe", currency: "EUR", phone: "+382" },
            { name: "Morocco", code: "MAR", iso2: "MA", capital: "Rabat", continent: "Africa", currency: "MAD", phone: "+212" },
            { name: "Mozambique", code: "MOZ", iso2: "MZ", capital: "Maputo", continent: "Africa", currency: "MZN", phone: "+258" },
            { name: "Myanmar", code: "MMR", iso2: "MM", capital: "Naypyidaw", continent: "Asia", currency: "MMK", phone: "+95" },
            { name: "Namibia", code: "NAM", iso2: "NA", capital: "Windhoek", continent: "Africa", currency: "NAD", phone: "+264" },
            { name: "Nauru", code: "NRU", iso2: "NR", capital: "Yaren", continent: "Oceania", currency: "AUD", phone: "+674" },
            { name: "Nepal", code: "NPL", iso2: "NP", capital: "Kathmandu", continent: "Asia", currency: "NPR", phone: "+977" },
            { name: "Netherlands", code: "NLD", iso2: "NL", capital: "Amsterdam", continent: "Europe", currency: "EUR", phone: "+31" },
            { name: "New Zealand", code: "NZL", iso2: "NZ", capital: "Wellington", continent: "Oceania", currency: "NZD", phone: "+64" },
            { name: "Nicaragua", code: "NIC", iso2: "NI", capital: "Managua", continent: "North America", currency: "NIO", phone: "+505" },
            { name: "Niger", code: "NER", iso2: "NE", capital: "Niamey", continent: "Africa", currency: "XOF", phone: "+227" },
            { name: "Nigeria", code: "NGA", iso2: "NG", capital: "Abuja", continent: "Africa", currency: "NGN", phone: "+234" },
            { name: "North Korea", code: "PRK", iso2: "KP", capital: "Pyongyang", continent: "Asia", currency: "KPW", phone: "+850" },
            { name: "North Macedonia", code: "MKD", iso2: "MK", capital: "Skopje", continent: "Europe", currency: "MKD", phone: "+389" },
            { name: "Norway", code: "NOR", iso2: "NO", capital: "Oslo", continent: "Europe", currency: "NOK", phone: "+47" },
            { name: "Oman", code: "OMN", iso2: "OM", capital: "Muscat", continent: "Asia", currency: "OMR", phone: "+968" },
            { name: "Pakistan", code: "PAK", iso2: "PK", capital: "Islamabad", continent: "Asia", currency: "PKR", phone: "+92" },
            { name: "Palau", code: "PLW", iso2: "PW", capital: "Ngerulmud", continent: "Oceania", currency: "USD", phone: "+680" },
            { name: "Panama", code: "PAN", iso2: "PA", capital: "Panama City", continent: "North America", currency: "PAB", phone: "+507" },
            { name: "Papua New Guinea", code: "PNG", iso2: "PG", capital: "Port Moresby", continent: "Oceania", currency: "PGK", phone: "+675" },
            { name: "Paraguay", code: "PRY", iso2: "PY", capital: "Asunción", continent: "South America", currency: "PYG", phone: "+595" },
            { name: "Peru", code: "PER", iso2: "PE", capital: "Lima", continent: "South America", currency: "PEN", phone: "+51" },
            { name: "Philippines", code: "PHL", iso2: "PH", capital: "Manila", continent: "Asia", currency: "PHP", phone: "+63" },
            { name: "Poland", code: "POL", iso2: "PL", capital: "Warsaw", continent: "Europe", currency: "PLN", phone: "+48" },
            { name: "Portugal", code: "PRT", iso2: "PT", capital: "Lisbon", continent: "Europe", currency: "EUR", phone: "+351" },
            { name: "Qatar", code: "QAT", iso2: "QA", capital: "Doha", continent: "Asia", currency: "QAR", phone: "+974" },
            { name: "Romania", code: "ROU", iso2: "RO", capital: "Bucharest", continent: "Europe", currency: "RON", phone: "+40" },
            { name: "Russia", code: "RUS", iso2: "RU", capital: "Moscow", continent: "Asia", currency: "RUB", phone: "+7" },
            { name: "Rwanda", code: "RWA", iso2: "RW", capital: "Kigali", continent: "Africa", currency: "RWF", phone: "+250" },
            { name: "Saint Kitts and Nevis", code: "KNA", iso2: "KN", capital: "Basseterre", continent: "North America", currency: "XCD", phone: "+1869" },
            { name: "Saint Lucia", code: "LCA", iso2: "LC", capital: "Castries", continent: "North America", currency: "XCD", phone: "+1758" },
            { name: "Saint Vincent and the Grenadines", code: "VCT", iso2: "VC", capital: "Kingstown", continent: "North America", currency: "XCD", phone: "+1784" },
            { name: "Samoa", code: "WSM", iso2: "WS", capital: "Apia", continent: "Oceania", currency: "WST", phone: "+685" },
            { name: "San Marino", code: "SMR", iso2: "SM", capital: "San Marino", continent: "Europe", currency: "EUR", phone: "+378" },
            { name: "São Tomé and Príncipe", code: "STP", iso2: "ST", capital: "São Tomé", continent: "Africa", currency: "STN", phone: "+239" },
            { name: "Saudi Arabia", code: "SAU", iso2: "SA", capital: "Riyadh", continent: "Asia", currency: "SAR", phone: "+966" },
            { name: "Senegal", code: "SEN", iso2: "SN", capital: "Dakar", continent: "Africa", currency: "XOF", phone: "+221" },
            { name: "Serbia", code: "SRB", iso2: "RS", capital: "Belgrade", continent: "Europe", currency: "RSD", phone: "+381" },
            { name: "Seychelles", code: "SYC", iso2: "SC", capital: "Victoria", continent: "Africa", currency: "SCR", phone: "+248" },
            { name: "Sierra Leone", code: "SLE", iso2: "SL", capital: "Freetown", continent: "Africa", currency: "SLL", phone: "+232" },
            { name: "Singapore", code: "SGP", iso2: "SG", capital: "Singapore", continent: "Asia", currency: "SGD", phone: "+65" },
            { name: "Slovakia", code: "SVK", iso2: "SK", capital: "Bratislava", continent: "Europe", currency: "EUR", phone: "+421" },
            { name: "Slovenia", code: "SVN", iso2: "SI", capital: "Ljubljana", continent: "Europe", currency: "EUR", phone: "+386" },
            { name: "Solomon Islands", code: "SLB", iso2: "SB", capital: "Honiara", continent: "Oceania", currency: "SBD", phone: "+677" },
            { name: "Somalia", code: "SOM", iso2: "SO", capital: "Mogadishu", continent: "Africa", currency: "SOS", phone: "+252" },
            { name: "South Africa", code: "ZAF", iso2: "ZA", capital: "Cape Town", continent: "Africa", currency: "ZAR", phone: "+27" },
            { name: "South Korea", code: "KOR", iso2: "KR", capital: "Seoul", continent: "Asia", currency: "KRW", phone: "+82" },
            { name: "South Sudan", code: "SSD", iso2: "SS", capital: "Juba", continent: "Africa", currency: "SSP", phone: "+211" },
            { name: "Spain", code: "ESP", iso2: "ES", capital: "Madrid", continent: "Europe", currency: "EUR", phone: "+34" },
            { name: "Sri Lanka", code: "LKA", iso2: "LK", capital: "Sri Jayawardenepura Kotte", continent: "Asia", currency: "LKR", phone: "+94" },
            { name: "Sudan", code: "SDN", iso2: "SD", capital: "Khartoum", continent: "Africa", currency: "SDG", phone: "+249" },
            { name: "Suriname", code: "SUR", iso2: "SR", capital: "Paramaribo", continent: "South America", currency: "SRD", phone: "+597" },
            { name: "Sweden", code: "SWE", iso2: "SE", capital: "Stockholm", continent: "Europe", currency: "SEK", phone: "+46" },
            { name: "Switzerland", code: "CHE", iso2: "CH", capital: "Bern", continent: "Europe", currency: "CHF", phone: "+41" },
            { name: "Syria", code: "SYR", iso2: "SY", capital: "Damascus", continent: "Asia", currency: "SYP", phone: "+963" },
            { name: "Taiwan", code: "TWN", iso2: "TW", capital: "Taipei", continent: "Asia", currency: "TWD", phone: "+886" },
            { name: "Tajikistan", code: "TJK", iso2: "TJ", capital: "Dushanbe", continent: "Asia", currency: "TJS", phone: "+992" },
            { name: "Tanzania", code: "TZA", iso2: "TZ", capital: "Dodoma", continent: "Africa", currency: "TZS", phone: "+255" },
            { name: "Thailand", code: "THA", iso2: "TH", capital: "Bangkok", continent: "Asia", currency: "THB", phone: "+66" },
            { name: "Timor-Leste", code: "TLS", iso2: "TL", capital: "Dili", continent: "Asia", currency: "USD", phone: "+670" },
            { name: "Togo", code: "TGO", iso2: "TG", capital: "Lomé", continent: "Africa", currency: "XOF", phone: "+228" },
            { name: "Tonga", code: "TON", iso2: "TO", capital: "Nukuʻalofa", continent: "Oceania", currency: "TOP", phone: "+676" },
            { name: "Trinidad and Tobago", code: "TTO", iso2: "TT", capital: "Port of Spain", continent: "North America", currency: "TTD", phone: "+1868" },
            { name: "Tunisia", code: "TUN", iso2: "TN", capital: "Tunis", continent: "Africa", currency: "TND", phone: "+216" },
            { name: "Turkey", code: "TUR", iso2: "TR", capital: "Ankara", continent: "Asia", currency: "TRY", phone: "+90" },
            { name: "Turkmenistan", code: "TKM", iso2: "TM", capital: "Ashgabat", continent: "Asia", currency: "TMT", phone: "+993" },
            { name: "Tuvalu", code: "TUV", iso2: "TV", capital: "Funafuti", continent: "Oceania", currency: "AUD", phone: "+688" },
            { name: "Uganda", code: "UGA", iso2: "UG", capital: "Kampala", continent: "Africa", currency: "UGX", phone: "+256" },
            { name: "Ukraine", code: "UKR", iso2: "UA", capital: "Kyiv", continent: "Europe", currency: "UAH", phone: "+380" },
            { name: "United Arab Emirates", code: "ARE", iso2: "AE", capital: "Abu Dhabi", continent: "Asia", currency: "AED", phone: "+971" },
            { name: "United Kingdom", code: "GBR", iso2: "GB", capital: "London", continent: "Europe", currency: "GBP", phone: "+44" },
            { name: "United States", code: "USA", iso2: "US", capital: "Washington, D.C.", continent: "North America", currency: "USD", phone: "+1" },
            { name: "Uruguay", code: "URY", iso2: "UY", capital: "Montevideo", continent: "South America", currency: "UYU", phone: "+598" },
            { name: "Uzbekistan", code: "UZB", iso2: "UZ", capital: "Tashkent", continent: "Asia", currency: "UZS", phone: "+998" },
            { name: "Vanuatu", code: "VUT", iso2: "VU", capital: "Port Vila", continent: "Oceania", currency: "VUV", phone: "+678" },
            { name: "Vatican City", code: "VAT", iso2: "VA", capital: "Vatican City", continent: "Europe", currency: "EUR", phone: "+379" },
            { name: "Venezuela", code: "VEN", iso2: "VE", capital: "Caracas", continent: "South America", currency: "VES", phone: "+58" },
            { name: "Vietnam", code: "VNM", iso2: "VN", capital: "Hanoi", continent: "Asia", currency: "VND", phone: "+84" },
            { name: "Yemen", code: "YEM", iso2: "YE", capital: "Sana'a", continent: "Asia", currency: "YER", phone: "+967" },
            { name: "Zambia", code: "ZMB", iso2: "ZM", capital: "Lusaka", continent: "Africa", currency: "ZMW", phone: "+260" },
            { name: "Zimbabwe", code: "ZWE", iso2: "ZW", capital: "Harare", continent: "Africa", currency: "ZWL", phone: "+263" }
        ];

        const countryEntities = countries.map(country => {
            return new Country().newInstanceToAdd(
                country.name,
                country.code,
                country.iso2,
                country.capital,
                country.continent,
                country.currency,
                country.phone
            );
        });

        await countryRepository.save(countryEntities);
        console.log(`Successfully seeded ${countryEntities.length} countries`);
    }
}